services:
  client:
    image: node:24-alpine
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev --host"
    container_name: gju-chatbot-client
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development
      VITE_PROXY_TARGET: http://api:8080

  api:
    image: maven:3.9-eclipse-temurin-25-alpine
    container_name: gju-chatbot-api
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JINA_API_KEY: ${JINA_API_KEY}
    command: sh -c "mvn -q -DskipTests dependency:resolve && mvn spring-boot:run"
    working_dir: /app
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: gju-chatbot-db
    environment:
      POSTGRES_DB: gju
      POSTGRES_USER: gju
      POSTGRES_PASSWORD: gju
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
