services:
  client:
    image: node:24-alpine
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev --host"
    container_name: gju-chatbot-client
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development
      VITE_PROXY_TARGET: http://api:8080

  api:
    image: maven:3.9-eclipse-temurin-25-alpine
    container_name: gju-chatbot-api
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JINA_API_KEY: ${JINA_API_KEY}
      CONVERTER_BASE_URL: http://converter:8000
    command: sh -c "mvn -q -DskipTests dependency:resolve && mvn spring-boot:run"
    working_dir: /app
    volumes:
      - ./api:/app
    depends_on:
      - db

  converter:
    image: python:3.12-slim
    container_name: gju-chatbot-converter
    working_dir: /app
    volumes:
      - ./converter:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y --no-install-recommends build-essential libxml2-dev libxslt1-dev libgl1 libglib2.0-0 &&
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: pgvector/pgvector:pg16-trixie
    container_name: gju-chatbot-db
    environment:
      POSTGRES_DB: gju
      POSTGRES_USER: gju
      POSTGRES_PASSWORD: gju
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
